spring:
  application:
    name: users-service
  datasource:
    username: 'postgres'
    password: 'postgres'
    url: 'jdbc:postgresql://localhost:5432/crisis-users'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 9898
  error:
    include-binding-errors: always
    include-message: always
    include-exception: true

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/

application:
  security:
    jwt:
      secret-key: 367639792F423F4528482B4D6251655468576D5A7134743777217A2543264629
      expiration: 10800000 # 3 hours
      refresh-token:
        expiration: 604800000 # 7 days
    cors:
      allowed-origins: http://localhost:8000