spring:
  application:
    name: users-service
  datasource:
    username: 'postgres'
    password: 'postgres'
    url: 'jdbc:postgresql://localhost:5432/crisis-users'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8081
  error:
    include-binding-errors: always
    include-message: always
    include-exception: true