spring:
  data:
    mongodb:
      uri: mongodb+srv://pouzani:1w1FYfKRGC5TDu5E@cluster0.z6te2vw.mongodb.net/?retryWrites=true&w=majority
      database: cluster0
  application:
    name: incident-service

server:
    port: 8082
    error:
      include-binding-errors: always
      include-message: always
      include-exception: true