spring:
  cloud:
    gateway:
      routes:
        - id: incident-service
          uri: lb://INCIDENT-SERVICE
          predicates:
            - Path=/incident/**

        - id: users-service
          uri: lb://USERS-SERVICE
          predicates:
            - Path=/user/** , /auth/**

        - id: chatgpt-service
          uri: lb://chatgpt-service
          predicates:
              - Path=/chatgpt/**

        - id: educational-service
          uri: lb://educational-service
          predicates:
              - Path=/articles/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
                - OPTIONS
            allowedHeaders: '*'
            exposedHeaders: '*'

  application:
    name: gateway-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8080



